spring:
  application:
    name: sample-webflux-http-netty
  main:
    banner-mode: "OFF"    

server:
  port: 8001
  
controller-sample:
  path: /controller-test
  
router-sample:
  path: /webflux-test